### ISSUE TITLE
NoSuchMethod Exception 

### ISSUE THREAD

**Issue by AndreasEK** [caseif/Steel#3]
We're running a craftbukkit 1.9 and getting a NoSuchMethod Exception. According to http://dev.bukkit.org/bukkit-plugins/steel/files/ the supported server version is 1.7.9, but apparently that method was changed in 1.7.10 (https://bukkit.atlassian.net/browse/BUKKIT-5668)

Any plans for a release to update the plugin?

**Comment by AndreasEK** [comment]
[10:13:13] [pool-3-thread-198/WARN]: org.apache.commons.lang.UnhandledException: Plugin Steel v1.2.0 generated an exception while executing task 263
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at net.caseif.flint.steel.lib.org.mcstats.Metrics.postPlugin(Metrics.java:335)
    at net.caseif.flint.steel.lib.org.mcstats.Metrics.access$400(Metrics.java:57)
    at net.caseif.flint.steel.lib.org.mcstats.Metrics$1.run(Metrics.java:223)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

**Comment by caseif** [comment]
Mm, seems Steel is still using an older revision of Metrics. I'll aim to get a hotfix out today. Thanks for catching this.

**Comment by AndreasEK** [comment]
unfortunatly, the M8 of mcstats is still in SNAPSHOT, but it fixes the exception.

**Comment by caseif** [comment]
Closed via e9f1082.
